### ISSUE TITLE
Local Development

### ISSUE THREAD

**Issue by riungemaina** [lhotanok/actor-ticketmaster-scraper#5]
How did you manage to develop and test this locally? is there a way to develop locally without deploying to apify each time I make a change?

**Comment by lhotanok** [comment]
You can use [Apify CLI](https://www.npmjs.com/package/apify-cli) for local development: 
```bash
npm -g install apify-cli
```
When you clone a new repository with Apify actor, you just need to install dependencies with `npm ci` and then initialize Apify local storage with `apify init`. You'll find a generated `storage` directory with `key_value_stores/default/INPUT.json` file where you can provide your input following actor's `INPUT_SCHEMA.json`. Dataset will be stored into `storage/datasets/default` in the form of individual JSON files.

Once the input is configured, you can run the scraper with `apify run -p`. Note that all storage files from the previous run will be removed.

Also, note that Ticketmaster scraper uses residential proxies by default (it is configured in `main.js`). You need to be logged into your Apify account and have access to residential proxies or change proxy configuration to use your own proxies. You can log in locally by running a command `apify login` (just once, to configure your global installation of Apify CLI).
I don't recommend running the scraper without proxies. I tried it and got my IP address banned multiple times. Fortunately, the ban was always just temporary, but it could have changed by now.
